port { AdSlot, Footer, MobileMenu, StoryCard } from "./ui";
import SiteImage from "./components/SiteImage";

export const dynamic = "force-static";
export const revalidate = 300;

const worlds = [
  { category: "TECNOLOGÍA + IA", tone: "tech" },
  { category: "GAMING", tone: "violet" },
  { category: "FINANZAS + CRIPTO", tone: "acid" },
  { category: "CÓMICS + SERIES", tone: "orange" },
].map((portal) => ({ ...portal, article: articles.find((article) => article.category === portal.category)! }));

 <><main className="classic-home">
    <header className="classic-header"><img src="/partners/nexo-referral-qr.jpeg" alt="Código QR del enlace de referido de Nexo" width="586" height="548" loading="lazy"/><span className="classic-brand-mark">T.</span><span>TOKEN<br/>GEEK<br/>COIN<small>.COM</small></span></a><nav aria-label="Navegación principal"><a href="/noticias">Noticias</a><a href="/ofertas">Ofertas Geek</a><a href="/comparadores">Comparadores</a><a href="/autor/ezequiel-guerrero">Sobre mí</a></nav><MobileMenu/></header>
    <section className="classic-banner" aria-label="Portada TokenGeekCoin"><SiteImage src="/channel-banner.webp" alt="TokenGeekCoin: gaming, inversiones, tecnología y cómics" width={1920} height={1080} sizes="100vw" priority/><div className="classic-banner-shade"/><a className="classic-banner-button" href="/noticias">Explorar noticias <span>→</span></a></section>
    <section className="classic-intro"><div className="classic-intro-copy"><p className="classic-kicker">GAMING · FINANZAS · TECNOLOGÍA · CULTURA GEEK</p><h1>Curiosidad en<br/><em>modo ON.</em></h1><p className="classic-lead">Un espacio personal para entender el multiverso digital, descubrir historias y tomar mejores decisiones sin apagar la pasión geek.</p><div className="classic-actions"><a className="classic-button" href="/noticias">Explorar noticias</a><a className="classic-link" href="/ofertas">Ver Ofertas Geek →</a></div></div><div className="classic-orbit" aria-hidden="true"><span className="classic-orbit-ring"/><span className="classic-orbit-core">T.</span><span className="classic-orbit-chip chip-one">XP</span><span className="classic-orbit-chip chip-two">₿</span><span className="classic-orbit-chip chip-three">AI</span></div></section>
    <div className="classic-marquee" aria-hidden="true"><span>JUGAR · APRENDER · INVERTIR · IMAGINAR · JUGAR · APRENDER · INVERTIR · IMAGINAR ·</span></div>
    <section className="classic-section classic-latest" id="noticias"><div className="classic-section-heading"><div><p className="classic-kicker">LO ÚLTIMO</p><h2>Explorar noticias</h2></div><a className="classic-link" href="/noticias">Ver todas →</a></div><div className="classic-lead-story"><a className="classic-lead-image" href={`/${articles[0].slug}`}><SiteImage src={articles[0].image} alt={articles[0].imageAlt || articles[0].title} width={1600} height={900} sizes="(max-width: 900px) 100vw, 55vw"/></a><div className="classic-lead-copy"><p className="classic-kicker">NUEVA · {articles[0].category}</p><h3><a href={`/${articles[0].slug}`}>{articles[0].title}</a></h3><p>{articles[0].dek}</p><span>{articles[0].date} · {articles[0].minutes} min de lectura</span><a className="classic-button" href={`/${articles[0].slug}`}>Leer la noticia</a></div></div><div className="classic-story-grid">{articles.slice(1,4).map(article=><StoryCard key={article.slug} article={article}/>)}</div></section>
    <section className="classic-section classic-territories"><div className="classic-section-heading"><div><p className="classic-kicker">CUATRO PUNTOS, UN MISMO UNIVERSO</p><h2>Mis territorios</h2></div></div><div className="classic-topic-grid"><a href="/tecnologia"><span>01</span><h3>Tecnología<br/>& IA</h3><p>Herramientas, futuro y cambios que ya están ocurriendo.</p></a><a href="/gaming"><span>02</span><h3>Gaming</h3><p>Lanzamientos, análisis y decisiones de compra.</p></a><a href="/finanzas"><span>03</span><h3>Finanzas<br/>& cripto</h3><p>Mercados y hábitos explicados sin humo.</p></a><a href="/comics"><span>04</span><h3>Cómics<br/>& series</h3><p>Historias, personajes y universos que vale explorar.</p></a></div></section>
    <section className="classic-section classic-world-section"><div className="classic-section-heading"><div><p className="classic-kicker">PORTALES DESTACADOS</p><h2>La última noticia de cada mundo</h2></div><a className="classic-link" href="/noticias">Ver todas →</a></div><div className="classic-world-grid">{worlds.map(world=><article className={`classic-world ${world.tone}`} key={world.category}><a className="classic-world-media" href={`/${world.article.slug}`}><SiteImage src={world.article.image} alt={world.article.imageAlt || world.article.title} width={1400} height={788} sizes="(max-width: 900px) 100vw, 50vw"/><span>Última noticia</span></a><div><p className="classic-kicker">{world.category}</p><h3><a href={`/${world.article.slug}`}>{world.article.title}</a></h3><p>{world.article.dek}</p><div className="classic-world-footer"><span>{world.article.date} · {world.article.minutes} min</span><a className="classic-link" href={`/${world.article.slug}`}>Leer ahora →</a></div></div></article>)}</div></section>
    <AdSlot format="leaderboard"/>
    <section className="classic-sponsor" aria-label="Sponsor Nexo"><div><p className="classic-kicker">SPONSOR · ENLACE DE REFERIDO</p><h2>Nexo, plataforma destacada para activos digitales</h2><p>Conocé sus productos y condiciones desde el enlace oficial de referido. Revisá siempre comisiones, riesgos y disponibilidad en tu país.</p><a className="classic-button" href="https://nexo.com/ref/qzvezbtobs?src=android-link" target="_blank" rel="sponsored noopener noreferrer">Visitar Nexo</a></div><a className="classic-qr" href="https://nexo.com/ref/qzvezbtobs?src=android-link" target="_blank" rel="sponsored noopener noreferrer"><img src="/partners/nexo-referral-qr.jpeg" alt="Código QR del enlace de referido de Nexo" loading="lazy"/><span>Escaneá o abrí el enlace de Nexo</span></a></section>
    <section className="classic-about" id="sobre-mi"><div><p className="classic-kicker">EL HUMANO DETRÁS DE LA PANTALLA</p><h2>Abogado de profesión,<br/><em>geek por elección.</em></h2></div><div><p>Soy Ezequiel Guerrero. Escribo desde Jujuy sobre tecnología, mercados, videojuegos, cómics y las ideas que conectan esos mundos.</p><div className="classic-socials"><a href="https://www.linkedin.com/in/eze-guerrero-06585142b/" target="_blank" rel="noopener noreferrer">Seguir en LinkedIn ↗</a><a href="https://www.youtube.com/@eztec3/videos?sub_confirmation=1" target="_blank" rel="noopener noreferrer">Suscribirse en YouTube ↗</a></div></div></section>
  </main><Footer/></>;
}
