import type {Metadata} from "next";import {AffiliateNotice,Footer,Header} from "../ui";
export const metadata:Metadata={title:"Comparadores",description:"Comparaciones independientes de consolas, monitores y wallets con criterios, límites y recomendaciones claras.",alternates:{canonical:"/comparadores"}};
const comparisons=[
  {title:"PlayStation 5 vs Xbox Series",dek:"Dos ecosistemas maduros: la decisión depende del catálogo, el presupuesto recurrente y dónde juega tu grupo.",a:"PlayStation 5",b:"Xbox Series",rows:[
    ["Catálogo","Fuerte en aventuras narrativas y exclusivas de PlayStation Studios.","Game Pass, retrocompatibilidad y lanzamientos propios dentro de la suscripción."],
    ["Control","DualSense suma respuesta háptica y gatillos adaptativos cuando el juego los aprovecha.","Diseño familiar, muy buena autonomía con pilas o batería reemplazable."],
    ["Modelos","Ediciones con disco y digital; revisar capacidad real antes de comprar.","Series X prioriza potencia; Series S reduce precio con límites de resolución y espacio."],
    ["Conviene si…","Buscás las franquicias de Sony y preferís comprar juegos individuales.","Valorás un catálogo amplio por suscripción y compatibilidad con generaciones anteriores."]]},
  {title:"Monitor 144 Hz vs 240 Hz",dek:"Más frecuencia no siempre significa una mejora visible equivalente al gasto.",a:"144 Hz",b:"240 Hz",rows:[
    ["Diferencia práctica","Salto muy perceptible desde 60 Hz y suficiente para la mayoría.","Mejora adicional más sutil, útil sobre todo en competencia de alto nivel."],
    ["Hardware necesario","Alcanzable por más GPU y juegos sin sacrificar tanta calidad.","Exige sostener cerca de 240 fps; resolución y calidad pueden tener que bajar."],
    ["Prioridad de compra","Buen equilibrio entre fluidez, resolución, panel y precio.","Primero revisar latencia, ghosting y consistencia; el número solo no alcanza."],
    ["Conviene si…","Jugás de todo, trabajás en la misma pantalla o cuidás presupuesto.","Competís en shooters y tu equipo ya entrega cuadros muy altos y estables."]]},
  {title:"Wallet con custodia vs autocustodia",dek:"La diferencia central no es una app: es quién controla las claves y quién puede recuperar el acceso.",a:"Con custodia",b:"Autocustodia",rows:[
    ["Control","La plataforma administra las claves y ejecuta los retiros.","El usuario controla la frase de recuperación y firma cada operación."],
    ["Recuperación","Suele permitir recuperar cuenta con verificación de identidad.","Perder la frase puede significar perder los fondos de forma definitiva."],
    ["Riesgo principal","Quiebra, congelamiento, hackeo o restricciones del proveedor.","Error humano, phishing, firma maliciosa o respaldo inseguro."],
    ["Conviene si…","Priorizás sencillez y entendés el riesgo de contraparte.","Necesitás control directo y podés mantener un procedimiento de seguridad probado."]]},
];
export default function Comparadores(){return <><Header/><main className="page"><header className="page-intro"><p className="eyebrow">COMPARADORES</p><h1>La decisión, lado a lado.</h1><p>Guías independientes para entender diferencias reales antes de gastar dinero o asumir riesgo. No elegimos un ganador universal: explicamos para quién conviene cada opción.</p><AffiliateNotice/><p className="updated">Criterios revisados el 9 de septiembre de 2026. Los precios y catálogos pueden cambiar.</p></header>{comparisons.map((comparison)=><section className="comparison" key={comparison.title} style={{marginBottom:48}}><div className="comparison-head"><div><span>COMPARACIÓN EDITORIAL</span><h2>{comparison.title}</h2></div><p>{comparison.dek}</p></div><div className="compare-table"><div className="compare-row head"><b>Criterio</b><b>{comparison.a}</b><b>{comparison.b}</b></div>{comparison.rows.map(([feature,a,b])=><div className="compare-row" key={feature}><b>{feature}</b><span>{a}</span><span>{b}</span></div>)}</div></section>)}<section className="trust"><h2>Cómo comparamos</h2><div><p><b>Necesidad antes que marca</b><br/>Partimos del uso, presupuesto y riesgo del lector, no de una lista de especificaciones.</p><p><b>Contexto verificable</b><br/>Revisamos documentación oficial y señalamos cuándo una condición puede cambiar.</p><p><b>Independencia</b><br/>Un enlace afiliado puede generar comisión, pero no compra una recomendación.</p></div></section></main><Footer/></>}
